### ISSUE TITLE
Function names prefixed with an underscore are treated as comments

### ISSUE THREAD

**Issue by rpowelll** [elixir-lang/language-elixir#81]
<img width="474" alt="screen shot 2016-10-12 at 10 22 44 pm" src="https://cloud.githubusercontent.com/assets/320910/19308330/a2391e68-90ca-11e6-874f-9b172e1b1e8b.png">

Like the title says, a call to a function whose name begins with an underscore character, such as in the example above, is incorrectly treated as a comment.

Here's what I get when logging the scope at line 3, column 42:

<img width="461" alt="screen shot 2016-10-12 at 10 23 50 pm" src="https://cloud.githubusercontent.com/assets/320910/19308346/b98149b0-90ca-11e6-8bb2-f05be41c3ffa.png">

**Comment by keathley** [comment]
They're marked as comments so that they are syntax highlighted correctly by atom themes. There is a PR to add an additional `variable` scope. Is there a specific issue that you're having with this?

**Comment by rpowelll** [comment]
Yeah I'm fairly new to Elixir so I'm still working out naming conventions, for what it's worth this program is copied pretty much verbatim from _Programing Elixir 1.3_. But this is still a syntactically legal name for a function, so I'd say highlighting it as an ignored pattern match is a bug.

**Comment by rkma** [comment]
I submitted #79 to handle cases like this. Would you mind taking a look at it, @keathley ?

**Comment by keathley** [comment]
@rkma I'm not sure how your PR resolves this. It marks everything starting with an underscore as an `other variable` which wouldn't syntax highlight in the same way that other functions are highlighted either.

In order to solve this we need to *not* identify unused variables outside of pattern matching. That means it'll need to work with function arguments, `case`, `cond`, and `=` (thats what I can come up with off the top of my head) but nothing else. The end result is that functions starting with underscores will be matched in the same way as any other variable. It also means that unused variables that are later used will be matched as variables. But using a variable marked as "unused" results in a compiler warning so it shouldn't be a huge deal.

Does anyone want to try their hand at this?

**Comment by ymtszw** [comment]
@keathley 
I was on the same boat in that we sometimes use functions with leading `_` to denote generated-and-used-behind-the-scenes functions.
So I have tried to implement that behavior but found it very cumbersome to cover perfectly.

Instead, I have found a band-aid solution which MIGHT suit for certain use cases.

Current pattern for unused variable:

```coffee
\\b_(\\w*)
```

Make it like this (could use some refinements):

```coffee
\\b_(\\w*)\\b(?!\\()
```

with this negative-lookahead, it won't match for `_`-prefixed strings when they are trailed by `(`,
which obviously denotes a beginning of function calling.
e.g.
```ex
# match for this '_unused' binding
_unused = some_function(:arg1)

# not match for this function name
_underscored_function_call(:arg1)
```

There are an obvious case which cannot be covered by this pattern: 0-arity function calls.
```ex
# matching; cannot distinguish whether it is a variable or a function
_underscored_no_arity_function_call
```

And I haven't come up with good solution to distinguish 0-arity function calls and variables/bindings (it is too hard for me to implement within regex pattern matching).

Thus I call it band-aid solution.
I heard that [in future versions of Elixir, `()`-less function call will be warned](https://github.com/elixir-lang/elixir/issues/3268).
When this comes into effect, people may start to change `()`-less function call to explicit style, 
and with it, the above negative-lookahead for trailing `(` might become sufficient, if not perfect, to distinguish unused variables and `_`-prefixed function calls.

Of course I haven't tested against all of the existing coding styles and use cases.
Would be glad if i can hear your thoughts. ❤️

**Comment by keathley** [comment]
@ymtszw Now that functions without parens are being warned we might be able to solve this. One use case that you'll have to watch out for though is when you have a function that comes after a pipe like: `|> _underscored_one_arity_function_call` since the parens are still optional at that point.

In general I guess I'm not sure what the utility of prefixing a function with `_` is. If its supposed to be a private function then you could just use `defp` or move the functionality to a different module.

Let me know what you think. If this is still an issue and you want to have a go at a PR then that would be great. Otherwise I'd like to close this issue. :smile: :+1:

**Comment by ymtszw** [comment]
Well I am not so enthusiastic about this issue since at the end of the day, `_`-prefixed functions are, if any, rare occasions in Elixir codes. And yes, one can simply use normally-named private functions or just put them in "behind the scene" modules.

Although with Elixir 1.4+, function calls with explicit parens became popular in my sight, so my proposed "band-aid" solution is now actually okay to have, I assume. I'll post PR later after checking it works as I described.

---

Concerning utility of `_`-prefixed functions - I agree that it does not have significant one.
An example use case I can come up with is [Phoenix.Router](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router.ex#L303), where various functions (including ones injected via `__using__/1` or `__before_compile__/1` macros) are doubly surrounded by `_`.

```ex
      @doc """
      Callback invoked by Plug on every request.
      """
      def call(conn, _opts) do
        conn
        |> prepare()
        |> __match_route__(conn.method, Enum.map(conn.path_info, &URI.decode/1), conn.host)
        |> Phoenix.Router.__call__()
      end
```

We MIGHT consider these double-`_`-surrounded functions/macros as an idiom for denoting "behind the scene interfaces that need to avoid name collision"?
But I don't assume it's widely accepted, nor used frequently in many library development. Heck, such naming should even be discouraged to language users since Elixir might introduce other predefined `_`-surrounded macros as compiler feature someday.

**Comment by ymtszw** [comment]
I had thought changing this
```cson
  {
    'match': '\\b_([\\w]+[?!]?)'
    'name': 'unused.comment.elixir'
  }
```
to this
```cson
  {
    'match': '\\b_([\\w]+[?!]?)\\b(?!\\()'
    'name': 'unused.comment.elixir'
  }
```
could exclude functions calls with negative lookahead.
Though it was partly okay, it turned out that it cannot nicely cover "underscored AND ?- or !-suffixed" function.
![2017-06-07 17 09 01](https://user-images.githubusercontent.com/4507126/26868483-1f21434e-4ba4-11e7-9441-a5cc6444484a.png)

Without word boundary character,
```cson
  {
    'match': '\\b_([\\w]+[?!]?)(?!\\()'
    'name': 'unused.comment.elixir'
  }
```
it stops matching at rightmost character which satisfies "not trailed by (" condition.
![2017-06-07 17 13 23](https://user-images.githubusercontent.com/4507126/26868643-b33c396c-4ba4-11e7-8bf7-c72b711b5733.png)

O my, this is frustrating! Perhaps positively matching for "proper function call syntax" may result in better result?
But that's somewhat different matter and possibly break some existing styling/theme. Since currently, function calls are "unscoped" in language-elixir (only default `source.elixir` scope attached).

I'm not pursuing this no further; you may close this for now. 😞 
Unless someone can come up with more precise regular expression to cover this pattern.

**Comment by keathley** [comment]
I totally understand how frustrating some of this stuff can be :smile:. Thanks for having a go at it. I'll go ahead and close this for now. We can revisit it later if we need to.
